config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'works#index'
  resources :works do
    resources :comics do
      resources :read_count, only: [:create]
    end
  end
  resources :users, only: [:show, :edit, :update]
  
  resources :book_marks, only: [:index, :create, :destroy]

  resources :inquiries, only: [:new, :create]

  resources :nices, only: [:create, :destroy]

  # ネストさせる
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one_attached :image
  has_many :works
  has_many :works, through: :book_marks
  has_many :book_marks
  has_many :read_counts, dependent: :destroy

  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
    
  validates :nickname, presence: true
  validates :profile, presence: true

  # フォローしたときの処理
  # Relationshipsの手前側（id側）に自動でcurrent_userの情報を保存する。
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :user_judge, only: [:edit, :update]

  def show
    #activehashのN+1問題の後に解決求む
    @works = Work.includes(:user).where(user_id: params[:id]).page(params[:page])
    @user = User.find(params[:id])
  end

  def edit
    
  end

  def update
    pattern = /^data:image\/(png|jpeg|jpg|gif);base64,([A-Za-z0-9+\/]+={0,2})$/
    if pattern =~ params[:user][:image]
      base64_data = params[:user][:image] # POSTリクエストからBase64データを受け取る
      base64_data = base64_data.split(',')[1] # ヘッダーを削除してBase64データのみを取得
      binary_data = Base64.decode64(base64_data)
      @user.image.attach(io: StringIO.new(binary_data), filename: 'user_image.png', content_type: 'image/png')
      if @user.update_without_password(user_params)
        redirect_to user_path(current_user.id), notice: 'User was successfully updated.'
      else
        render :edit
      end
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :profile)
  end

  def user_judge
    if params[:id] == current_user[:id].to_s
      @user = User.find(params[:id])
    else
      redirect_to root_path
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<header>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.13/cropper.css"
    integrity="sha512-C4k/QrN4udgZnXStNFS5osxdhVECWyhMsK1pnlk+LkC7yJGCqoYxW4mH3/ZXLweODyzolwdWSqmmadudSHMRLA=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.13/cropper.js"
      integrity="sha512-LjPH94gotDTvKhoxqvR5xR2Nur8vO5RKelQmG52jlZo7SwI5WLYwDInPn1n8H9tR0zYqTqfNxWszUEy93cHHwg=="
      crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</header>

<h2 class = "form-title">ユーザー情報変更</h2>

<%= form_with(model: @user, local: true) do |f| %>
  <div class="container">
    <div class="row justify-content-center">

      <div class="col-10">
        <h5 class="my-1">ヘッダー画像</h5>
        <%= f.file_field :ignore_image, class: "edit-form-image", id:"image_input"%>
      </div>

      <!--設定していない場合グレー画像とか-->
      <%= image_tag(@user.image, id: "header_preview", class: "h-100 col-10 pb-3") %>

      <div class="modal" id="headerCropModal" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered modal-lg">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5">ヘッダー画像編集</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="閉じる"></button>
            </div>
            <div class="modal-body row">
              <div id="image_preview" class="justify-content-evenly">
                <div class="col-6">
                  <img id="target" src="" class="w-100">
                </div>
                <div class="col-6">
                  <img id='preview' src="" class='w-100'>
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" id="header_close">閉じる</button>
              <button type="button" class="btn btn-primary" id="header_submit">変更を保存</button>
            </div>
          </div>
        </div>
      </div>

      <%= f.hidden_field :image, id: "cropped_image_data"%>

      <div class="col-10 pb-3">
        <h5 class="my-1">ニックネーム</h5>
        <%= f.text_field :nickname, autofocus: true, placeholder: "ニックネーム", class: "field-form" %>
      </div>

      <div class="col-10 pb-3">
        <h5 class="my-1">プロフィール</h5></h5>
        <%= f.text_area :profile, autocomplete: "new-password", placeholder: "プロフィール", class: "field-area" %>
      </div>

      <div class="actions">
        <%= f.submit "プロフィール情報変更" %>
      </div>
    </div>
  </div>

<script>
  imageElement = document.getElementById("image_input");
  let cropper = null;
  const headerCropModal = new bootstrap.Modal(document.getElementById("headerCropModal"));
  imageElement.addEventListener("change", function (e) {
    const preview = document.getElementById("image_preview");
    const targetImg = document.getElementById("target");
    const croppedPreview = document.getElementById("preview")
    let croppedImageData;
    preview.style.display = "flex"

    if(e.target.files[0] == null)
    {
      return;
    }

    headerCropModal.show();

    const file = e.target.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = function (event) {
        targetImg.src = event.target.result;
        cropper = new Cropper(targetImg, {aspectRatio: 3 / 1});
      }
      reader.readAsDataURL(file);

      targetImg.addEventListener('ready', function(){
        let canvas = cropper.getCroppedCanvas();
        if(canvas !== null)
        {
          croppedImageData = canvas.toDataURL();

          croppedPreview.src = croppedImageData;
        }
      });

      targetImg.addEventListener('cropend', function(){
        let canvas = cropper.getCroppedCanvas();
        if(canvas !== null)
        {
          croppedImageData = canvas.toDataURL();
  
          croppedPreview.src = croppedImageData;
        }
      });

      document.getElementById("header_submit").addEventListener("click", function(){
        document.getElementById("cropped_image_data").value = croppedImageData;
        document.getElementById("header_preview").src = croppedImageData;
        cropper.destroy();
        headerCropModal.hide();
        canvas = null;
        croppedImageData = null;
        imageElement.value = null;
      });

      document.getElementById("header_close").addEventListener("click", function()
      {
        cropper.destroy();
        headerCropModal.hide();
        canvas = null;
        croppedImageData = null;
        imageElement.value = null;
      });
    } else {
      targetImg.src = ""; // ファイルが未選択の場合はプレビューをクリア
      preview.style.display = "none"; // プレビューコンテナを非表示
      cropperControls.style.display = "none"; // クロップコントロールを非表示
    }
  });
</script>

<% end %>

app/views/users/show.html.erb
  <div class="container">
    <div class="row align-items-center">
      <% if @user.image.attached? %>
      <%# ここのcss変更しました。違和感がないように %>
      <%= image_tag(@user.image, class: "my-page-image h-100 m-0 col-12") %>
      <% else %>
      <%# ノーイメージを貼る %>
      <% end %>
      <div class="col-9 col-md-10 my-1">
        <%= content_tag :div, @user.nickname, class: "my-page-name" %>
      </div>
      <div class="col-3 col-md-2 border rounded-pill my-1 py-1 text-center">
        <% if @user.id == current_user.id %>
          <%= link_to "編集", edit_user_path(@user) %>
        <% elsif current_user.following?(@user) %>
          <%= link_to "フォロー外す", user_relationships_path(@user.id), method: :delete %>
        <% else %>
          <%= link_to "フォローする", user_relationships_path(@user.id), method: :post %>
        <% end %>
      </div>
      <div class="mb-3">
        <%= content_tag :div, @user.profile, class: "col-12" %>
      </div>
    </div>
  </div>

  <%#= render partial: 'shared/main-list', locals: { works: @works } %>
  <div class="container">
    <hr>
    <h3 class="p-2">投稿作品一覧</h3>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3  g-2" id="wrapper">
    <% @works.each_with_index do |work, index| %>
      <div class="col">
        <div class="card">
          <div class='position-relative'>
            <%= link_to work_comics_path(work_id: work.id), class: 'stretched-link' do %>
            <%= image_tag(work.image, class: "card-img object-fit-contain", style: "height:262px;") %>
            <% end %>
          </div>
          <div class="card-img-overlay d-flex flex-column">
            <div class="card-title"><%= work.main_title %></div>
            <div class="card-subtitle mh-50">
              <small class="text-body-secondary"><%= work.category.name %></small>
              <small class="text-body-secondary"><%= work.evaluation %></small>
            </div>
          </div>

          <div class="card-footer mt-auto position-relative">
            <% if user_signed_in? %>
            <% unless work.book_marks.find_by(user_id: current_user[:id]) %>
            <%= link_to book_marks_path(id: work.id), method: :post, class: 'stretched-link' do %>
            <button type='button' class='btn btn-sm btn-outline-secondary position-relative'>ブックマーク登録</button>
            <% end %>
            <% else %>
            <%= link_to book_mark_path(work.book_marks.find_by(user_id: current_user[:id])), method: :delete, class: 'stretched-link' do %>
            <button type='button' class='btn btn-sm btn-outline-secondary position-relative'>ブックマーク削除</button>
            <% end %>
            <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    </div>

  <%= paginate @works %>