config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'works#index'
  resources :works do
    resources :comics do
      resources :read_count, only: [:create]
    end
  end
  resources :users, only: [:show, :edit, :update]
  
  resources :book_marks, only: [:index, :create, :destroy]

  resources :inquiries, only: [:new, :create]

  resources :nices, only: [:create, :destroy]

  # ネストさせる
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
end

app/models/comic.rb
class Comic < ApplicationRecord
  belongs_to :work
  # has_many :comments, dependent: :destroy
  # has_one_attached :image
  has_many_attached :images
  has_many :read_counts, dependent: :destroy
  has_many :nices, dependent: :destroy

  # validates :image, presence: true
  validates :images, presence: true
  validate :validate_image_count
  def validate_image_count
    errors.add(:images, "は1枚以上50枚以下にしてください") if images.length < 1 || images.length > 50
  end
  validates :subtitle, presence: true
  validates :subtitle, length: { minimum: 1, maximum: 100, message: "は1文字以上100文字以下にしてください" }
  validates :work_id, presence: true
  validates :explanation, presence: true
  validates :explanation, length: { minimum: 1, maximum: 70000, message: "は1文字以上70000文字以下にしてください" }

  # @comic.view_countとすることで、閲覧者数が返り値として返ってきます。（comicは、一つのデータね。）
  def view_count
    read_counts.count
  end

end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
    before_action :authenticate_user!, only: [:create, :new, :edit, :update, :destroy]
    before_action :comic_judge, only: [:edit, :update, :destroy]

    def index
        @comics = Comic.includes(:work).where(work_id: params[:work_id])
        @work = Work.find(params[:work_id])
        sequence = 1.step
    end

    def new
        @comic = Comic.new
        @work = Work.find(params[:work_id])
    end

    def create
        @comic = Comic.new(comic_params)
        @work = Work.find(params[:work_id])
        if @comic.save
            redirect_to work_comics_path(@work)
        else
            render "new"
        end
    end

    def show
        @comic = Comic.find(params[:id])
        images = @comic.images
        @comic = Comic.find(params[:id])
        # # unlessは、ifの逆です。見つからなかったら実行、つまり一人１カウントって意味です。
        # unless ReadCount.find_by(user_id: current_user.id, comic_id: @comic.id)
        #     current_user.read_counts.create(comic_id: @comic.id)
        # end
        # 60秒経ったら１カウント
    end

    def edit
    end
    
    def update
        if @comic.update(comic_params)
            redirect_to  work_comics_path(@work, @comic)
        else
            render 'edit'
        end
    end
    
    def destroy
        @comic.destroy
        redirect_back(fallback_location: root_path)
    end

    private

    def comic_judge
        if Work.find(params[:work_id]).user[:id] == current_user[:id]
            @comic = Comic.find(params[:id])
            @work = Work.find(params[:work_id])
        else
            redirect_to root_path
        end
    end
    
    def comic_params
        params.require(:comic).permit(:subtitle, :explanation, {images: []}).merge(work_id: params[:work_id])
    end
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/views/comics/edit.html.erb
<div class="form">
  <div class="main-new-form">編集</div>

  <%= form_with(model: [@work, @comic], id: "new_post", local: true) do |form| %>
    <div class="main-form">
      <%= form.label :"サブタイトル (100文字以内で入力)", class: "main-label" %>
      <%= form.text_field :subtitle, class: "main-form-text", id: "main-text" %>
    </div>
    <div classs="main-form">
      <%= form.label :"説明文 (70000文字以内で入力)", class: "main-label" %>
      <%= form.text_area :explanation, class: "main-form-area", id: "main-area" %>
    </div>
    <div class="count", id="title-count">タイトル文字数 : 0字</div>
    <div class="count", id="explanation-count">説明文文字数 : 0字</div>
    <div class="main-form">
      <div class="main-file">
        <%= form.label :"新巻絵(下スクロール)", class: "main-label" %>
        <div id="previews"></div>
        <div class="mb-3">
          <%= label_tag "formFileMultiple", "複数ファイル選択の例", class: "form-label" %>
          <%= form.file_field :images, multiple: true, class: "form-control", id: "formFileMultiple" %>
        </div>
      </div>
    </div>
    <div class="main-form">
      <%= form.submit "編集保存", class: "main-submit" %>
    </div>
  <% end %>
</div>

app/views/comics/index.html.erb
<div class="comic-index-body">
  <div class="comic-main">
    <%= image_tag @work.image, class: "comic-main-image" %>
    <%= content_tag :h1, @work.main_title, class: "comic-main-title" %>
    <%= content_tag :div, @work.user.nickname, class: "comic-nickname" %>
    <%= content_tag :div, @work.explanation, class: "comic-explanation" %>
    <div class="wrapper">
      <%# 本当は警告通知を出す %>
      <% if user_signed_in? && current_user == @work.user %>
        <%= button_to "作品削除", work_path(id: @work.id), method: :delete, class: "delete-button" %>
        <%= link_to "作品編集", edit_work_path(id: @work.id), class: "edit-button" %>
      <% end %>
    </div>
  </div>
  <% @comics.each_with_index do |comic, i| %>
    <%= link_to work_comic_path(id: comic), class: "comic-part" do %>
      <%= image_tag comic.images[0], class: "comic-image" %>
      <%= "[第" + (i + 1).to_s + "話]" + comic.subtitle %>
    <% end %>

    <% if user_signed_in? %>
      <% unless comic.nices.find_by(user_id: current_user[:id]) %>
        <%= button_to "いいね登録", nices_path(id: comic[:id]), method: :post, class: "delete-button" %>
      <% else %>
        <%= button_to "いいね削除", nice_path(id: comic[:id]), method: :delete, class: "delete-button" %>
      <% end %>
    <% end %>

    <div class="comic-wrapper">
      <% if user_signed_in? && current_user == @work.user %>
        <%= button_to "[第" + (i + 1).to_s + "話]" + "削除", work_comic_path(@work, comic), method: :delete, class: "delete-button" %>
        <%= link_to "[第" + (i + 1).to_s + "話]" + "編集", edit_work_comic_path(@work, comic), class: "edit-button" %>
      <% end %>
    </div>
    
  <% end %>
  <% if user_signed_in? && current_user == @work.user %>
    <%= link_to "新話作成", new_work_comic_path(@work), class: "new-link" %>
  <% end %>
</div>

app/views/comics/new.html.erb
<div class="form">
  <div class="main-new-form">新巻作成</div>

  <%= form_with(model: [@work, @comic], id: "new_post", local: true) do |form| %>
    <div class="main-form">
      <%= form.label :"サブタイトル (100文字以内で入力)", class: "main-label" %>
      <%= form.text_field :subtitle, class: "main-form-text", id: "main-text" %>
    </div>
    <div classs="main-form">
      <%= form.label :"説明文 (70000文字以内で入力)", class: "main-label" %>
      <%= form.text_area :explanation, class: "main-form-area", id: "main-area" %>
    </div>
    <div class="count", id="title-count">タイトル文字数 : 0字</div>
    <div class="count", id="explanation-count">説明文文字数 : 0字</div>
    <div class="main-form">
      <div class="main-file">
        <%= form.label :"新巻絵(下スクロール)", class: "main-label" %>
        <div id="previews"></div>
        <div class="mb-3">
          <%= label_tag "formFileMultiple", "複数ファイル選択の例", class: "form-label" %>
          <%= form.file_field :images, multiple: true, class: "form-control", id: "formFileMultiple" %>
        </div>
      </div>
    </div>
    <div class="main-form">
      <%= form.submit "新規保存", class: "main-submit" %>
    </div>
  <% end %>
</div>

app/views/comics/show.html.erb
<div class="comic-show-desktop">
  <div id="carouselExampleControls" class="carousel slide" data-bs-wrap="false">
    <div class="carousel-inner">
      <% if (@comic.images.size().to_f % 2) == 0 %>
        <% ((@comic.images.size().to_f / 2).round - 1).downto(0) do |index| %>
          <% if index == 0 %>
            <div class="carousel-item active">
              <div class="d-flex justify-content-center bg-dark">
                <div class="col-6 left-wrapper">
                  <%= image_tag @comic.images[index * 2 + 1], class: "left image", id: "comic-image" %>
                </div>
                <div class="col-6">
                  <%= image_tag @comic.images[index * 2], class: "image", id: "comic-image" %>
                </div>
              </div>
            </div>
          <% else %>
            <div class="carousel-item">
              <div class="d-flex justify-content-center bg-dark">
                <div class="col-6 left-wrapper">
                  <%= image_tag @comic.images[index * 2 + 1], class: "left image", id: "comic-image" %>
                </div>
                <div class="col-6">
                  <%= image_tag @comic.images[index * 2], class: "image", id: "comic-image" %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      <% else %>
        <% ((@comic.images.size().to_f / 2).round - 1).downto(0) do |index| %>
          <% if ((@comic.images.size().to_f / 2).round) == 1 %>
            <div class="carousel-item active">
              <div class="d-flex justify-content-center bg-dark">
                <div class="col-6 left-wrapper">
                </div>
                <div class="col-6">
                  <%= image_tag @comic.images[index * 2], class: "image", id: "comic-image" %>
                </div>
              </div>
            </div>
          <% elsif ((@comic.images.size().to_f / 2).round - 1) == index %>
            <div class="carousel-item">
              <div class="d-flex justify-content-center bg-dark">
                <div class="col-6 left-wrapper">
                </div>
                <div class="col-6">
                  <%= image_tag @comic.images[index * 2], class: "image", id: "comic-image"  %>
                </div>
              </div>
            </div>
          <% elsif index == 0 %>
            <div class="carousel-item active">
              <div class="d-flex justify-content-center bg-dark">
                <div class="col-6 left-wrapper">
                  <%= image_tag @comic.images[index * 2 + 1], class: "left image", id: "comic-image" %>
                </div>
                <div class="col-6">
                  <%= image_tag @comic.images[index * 2], class: "image", id: "comic-image" %>
                </div>
              </div>
            </div>
          <% else %>
            <div class="carousel-item">
              <div class="d-flex justify-content-center bg-dark">
                <div class="col-6 left-wrapper">
                  <%= image_tag @comic.images[index * 2 + 1], class: "left image", id: "comic-image" %>
                </div>
                <div class="col-6">
                  <%= image_tag @comic.images[index * 2], class: "image", id: "comic-image"  %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <button type="button" class="carousel-control-prev" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">前へ</span>
    </button>
    <button type="button" class="carousel-control-next" data-bs-target="#carouselExampleControls" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">次へ</span>
    </button>
  </div>
</div>


<div class="comic-show-mobile">
  <div id="carouselExampleControls-mobile" class="carousel slide" data-bs-wrap="false">
    <div class="carousel-inner">
      <% (@comic.images.size() - 1).downto(0) do |index| %>
        <% if index == 0 %>
          <div class="carousel-item active">
            <div class="d-flex justify-content-center bg-dark">
              <%= image_tag @comic.images[index], class: "mobile-image", id: "mobile-image" %>
            </div>
          </div>
        <% else %>
          <div class="carousel-item">
            <div class="d-flex justify-content-center bg-dark">
              <%= image_tag @comic.images[index], class: "mobile-image", id: "mobile-image" %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <button type="button" class="carousel-control-prev" data-bs-target="#carouselExampleControls-mobile" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">前へ</span>
    </button>
    <button type="button" class="carousel-control-next" data-bs-target="#carouselExampleControls-mobile" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">次へ</span>
    </button>
  </div>
</div>