config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'works#index'
  resources :works do
    resources :comics do
      resources :read_count, only: [:create]
    end
  end
  resources :users, only: [:show, :edit, :update]
  
  resources :book_marks, only: [:index, :create, :destroy]

  resources :inquiries, only: [:new, :create]

  resources :nices, only: [:create, :destroy]

  # ネストさせる
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book_mark.rb
class BookMark < ApplicationRecord
  belongs_to :user
  belongs_to :work
  
  validates :user_id, presence: true
  validates :work_id, presence: true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '恋愛' },
    { id: 3, name: '文芸' },
    { id: 4, name: 'ファンタジー' },
    { id: 5, name: 'SF' },
    { id: 6, name: '異世界転生/転移' },
    { id: 7, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :works
end

app/models/comic.rb
class Comic < ApplicationRecord
  belongs_to :work
  # has_many :comments, dependent: :destroy
  # has_one_attached :image
  has_many_attached :images
  has_many :read_counts, dependent: :destroy
  has_many :nices, dependent: :destroy

  # validates :image, presence: true
  validates :images, presence: true
  validate :validate_image_count
  def validate_image_count
    errors.add(:images, "は1枚以上50枚以下にしてください") if images.length < 1 || images.length > 50
  end
  validates :subtitle, presence: true
  validates :subtitle, length: { minimum: 1, maximum: 100, message: "は1文字以上100文字以下にしてください" }
  validates :work_id, presence: true
  validates :explanation, presence: true
  validates :explanation, length: { minimum: 1, maximum: 70000, message: "は1文字以上70000文字以下にしてください" }

  # @comic.view_countとすることで、閲覧者数が返り値として返ってきます。（comicは、一つのデータね。）
  def view_count
    read_counts.count
  end

end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
    belongs_to :user

    validates :inquiry, presence: true
    validates :inquiry, length: { minimum: 1, maximum: 70000, message: "は1文字以上70000文字以下にしてください" }
end

app/models/nice.rb
class Nice < ApplicationRecord
  belongs_to :user
  belongs_to :comic
  
end

app/models/read_count.rb
class ReadCount < ApplicationRecord
  belongs_to :user
  belongs_to :comic
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  # class_name: "User"でUserモデルを参照
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one_attached :image
  has_many :works
  has_many :works, through: :book_marks
  has_many :book_marks
  has_many :read_counts, dependent: :destroy

  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
    
  validates :nickname, presence: true
  validates :profile, presence: true

  # フォローしたときの処理
  # Relationshipsの手前側（id側）に自動でcurrent_userの情報を保存する。
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :user
  has_many :comics, dependent: :destroy
  has_many :users, through: :book_marks
  has_many :book_marks, dependent: :destroy
  has_one_attached :image

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category

  #ジャンルの選択が「---」の時は保存できないようにする
  validates :user_id, presence: true
  validates :category_id, numericality: { other_than: 1 , message: "can't be blank"}
  validates :main_title, presence: true
  validates :main_title, length: { minimum: 1, maximum: 100, message: "is more than 100characters" }
  validates :explanation, presence: true
  validates :explanation, length: { minimum: 1, maximum: 70000, message: "is more than 70000characters" }

end

app/controllers/nices_controller.rb
class NicesController < ApplicationController

  def index
    # ログインしているuserのブックマークを抽出
    @nices = Nice.where("user_id = ?", current_user[:id])
    # ブックマークと関連するworkをarrayに格納
    @comics = []
    @nices.each do |nice|
      @comics.push(Comic.find(nice.comic_id))
    end
  end

  def create
    unless Nice.find_by(user_id: current_user[:id], comic_id: params[:id])
      Nice.create(user_id: current_user[:id], comic_id: params[:id])
      @comic = Comic.find(params[:id])
      @work = Work.find(@comic.work_id)
      if @work[:evaluation].nil?
        @work[:evaluation] = 0
      end
      @work[:evaluation] += 1
      @work.save
    end
    redirect_back(fallback_location: root_path)
  end

  def destroy
    # 消す予定のブックマークのidを送ってもらう予定
    @nice = Nice.find_by(user_id: current_user[:id], comic_id: params[:id])
    # saveと挙動はほぼ同じ
    unless @nice.nil?
      @work = Work.find(@nice.comic.work_id)
      @nice.destroy
      if @work[:evaluation].nil?
        @work[:evaluation] = 0
      else
        @work[:evaluation] -= 1
      end
      @work.save
    end
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :user_judge, only: [:edit, :update]

  def show
    #activehashのN+1問題の後に解決求む
    @works = Work.includes(:user).where(user_id: params[:id]).page(params[:page])
    @user = User.find(params[:id])
  end

  def edit
    
  end

  def update
    pattern = /^data:image\/(png|jpeg|jpg|gif);base64,([A-Za-z0-9+\/]+={0,2})$/
    if pattern =~ params[:user][:image]
      base64_data = params[:user][:image] # POSTリクエストからBase64データを受け取る
      base64_data = base64_data.split(',')[1] # ヘッダーを削除してBase64データのみを取得
      binary_data = Base64.decode64(base64_data)
      @user.image.attach(io: StringIO.new(binary_data), filename: 'user_image.png', content_type: 'image/png')
      if @user.update_without_password(user_params)
        redirect_to user_path(current_user.id), notice: 'User was successfully updated.'
      else
        render :edit
      end
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :profile)
  end

  def user_judge
    if params[:id] == current_user[:id].to_s
      @user = User.find(params[:id])
    else
      redirect_to root_path
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_marks_helper.rb
module BookMarksHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/nices_helper.rb
module NicesHelper
end

app/helpers/read_counts_helper.rb
module ReadCountsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>BecomeManga</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_pack_tag 'application' %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous">
  </script>
</head>

<body style="padding-top:4.4rem">
  <header> 
    <nav class="navbar bg-body-tertiary fixed-top">
      <div class="container-fluid">
        <%= link_to "漫画家になろう", root_path, class: "navber-brand title" %>
        <button type="button" class="navbar-toggler" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar"
          aria-expanded="false" aria-controls="offcanvasNavbar" aria-label="ナビゲーションの切替">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasNavbarLabel">メニュー</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="閉じる"></button>
          </div>
          <div class="offcanvas-body">
            <div class="navbar-nav justify-content-end flex-grow-1 pe-3">
                  <%if user_signed_in? %>
                    <div class="row">
                      <div class="col-5">
                        <%= link_to "マイページ", user_path(current_user), class: "login" %>
                      </div>
                      <div class="col-5">
                        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "registration" %>
                      </div>
                    </div>
                  <% else %>
                    <div class="row">
                      <div class="col-5">
                        <%= link_to "ログイン", new_user_session_path, class: "login" %>
                      </div>
                      <div class="col-5">
                        <%= link_to "新規登録", new_user_registration_path, class: "registration" %>
                      </div>
                    </div>
                  <% end %>
                <%= link_to "新規漫画作成", new_work_path(), class: "nav-link" %>
                <%= link_to "ランキング", works_path(), class: "nav-link" %>
                <%= link_to "追加漫画作成", "#", class: "nav-link" %>
                <%= link_to "マイプロフィール", "#", class: "nav-link", id: "my-profile", remote: true %>
                <%= link_to "ブックマーク一覧", book_marks_path(), class: "nav-link" %>
                <%= link_to "お問い合わせ", new_inquiry_path(), class: "nav-link" %>
            </div>
          </div>
        </div>
      </div>
    </nav>
    </header>
    <%= yield %>
</body>

</html>

app/views/shared/_main-list.html.erb
<div>一覧機能
  <% @works.each do |work| %>
    <div><br>
      <%= work.main_title %><br>
      <%= work.explanation %><br>
      <%= work.category.name %><br>
    </div><br>
  <% end %>
</div>

app/views/shared/_my-page.html.erb
<div class="my-page">
  <div>
    <% if user.image.attached? %>
      <%# ここのcss変更しました。違和感がないように %>
      <%= image_tag(user.image, class: "my-page-image") %>
    <% else %>
      <%# ノーイメージを貼る %>
    <% end %>
    <% if user.id == current_user.id %>
    <%= link_to "編集", edit_user_path(user), class: "my-page-edit" %>
    <% end %>
  </div>
  <div class="my-page-header">
    <%= content_tag :div, user.nickname, class: "my-page-name" %>
  </div>
  <h1 class="topic-profile">自己紹介</h1>
  <%= content_tag :div, user.profile, class: "my-page-profile" %>
</div>